name: BUILD

on:
  [ push ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ğŸ›ï¸
      uses: actions/checkout@v2.3.4
      
    steps:
    - name: Flutter action
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.2'
      run: |
        flutter pub get
        flutter test
        flutter build web

    - name: Build ğŸ› 
      working-directory: ./client/
      run: flutter build web
        
    - name: NoJekyll âŒ
      run: touch ./client/build/web/.nojekyll
    
    - name: Deploy ğŸš€
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        BRANCH: gh-pages
        FOLDER: ./client/build/web/
