name: RELEASE

on:
  push

jobs:
  check-detector:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ğŸ›ï¸
      uses: actions/checkout@v2.3.4 
    
    - name: Fetch Github Release Asset
      uses: dsaltares/fetch-gh-release-asset@0.06
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        file: "hogweed-detector.tflite"
        target: "./hogweed-detector.tflite"
        
    - name: Install Dependencies
      run: |
        cd ./ml-helper
        pip3 install --user pipenv
        pipenv install --skip-lock --system
        nbstripout --install

    - name: Test Detector 
      run: python3 ./ml-helper/test.py -n ./hogweed-detector.tflite -s ./ml-helper/datasets/test.csv
